name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: yarn

      - name: Create Build
        run: yarn build

      - name: Publish to NPM
        run: npm publish ./dist
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
